apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: agent-sandbox-pool
  namespace: sandbox-devspaces
spec:
  replicas: 3
  sandboxTemplateRef:
    name: secure-agent-sandbox
