name: docs

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/docs.yml
    - site.yml
    - 'documentation/**'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build site
      run: |
        npx antora@3.1 site.yml
        touch gh-pages/.nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: "${{github.token}}"
        FOLDER: gh-pages
        BRANCH: gh-pages
        commit-message: "[docs] Publishing the docs for commit(s) ${{github.sha}}"
